create table jobs (
	job_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	job text NOT NULL
);

create table educations (
	education_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	education text NOT NULL,
	seq integer NOT NULL
);

create table users (
	user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	email text NOT NULL UNIQUE,
	first_name text NOT NULL,
	last_name text NOT NULL,
	phone text,
	address text,
	job_id integer REFERENCES jobs (job_id),
	education_id integer REFERENCES educations (education_id),
	created_at timestamptz NOT NULL DEFAULT now()
);
